// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.netty.study.proto;

/**
 * Protobuf type {@code com.netty.study.proto.GetStudentByUserTypeReq}
 */
public  final class GetStudentByUserTypeReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.netty.study.proto.GetStudentByUserTypeReq)
    GetStudentByUserTypeReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetStudentByUserTypeReq.newBuilder() to construct.
  private GetStudentByUserTypeReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetStudentByUserTypeReq() {
    usertype_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetStudentByUserTypeReq();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetStudentByUserTypeReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            usertype_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.netty.study.proto.StudentProto.internal_static_com_netty_study_proto_GetStudentByUserTypeReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.netty.study.proto.StudentProto.internal_static_com_netty_study_proto_GetStudentByUserTypeReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.netty.study.proto.GetStudentByUserTypeReq.class, com.netty.study.proto.GetStudentByUserTypeReq.Builder.class);
  }

  public static final int USERTYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object usertype_;
  /**
   * <code>string usertype = 1;</code>
   * @return The usertype.
   */
  public java.lang.String getUsertype() {
    java.lang.Object ref = usertype_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      usertype_ = s;
      return s;
    }
  }
  /**
   * <code>string usertype = 1;</code>
   * @return The bytes for usertype.
   */
  public com.google.protobuf.ByteString
      getUsertypeBytes() {
    java.lang.Object ref = usertype_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      usertype_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getUsertypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, usertype_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUsertypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, usertype_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.netty.study.proto.GetStudentByUserTypeReq)) {
      return super.equals(obj);
    }
    com.netty.study.proto.GetStudentByUserTypeReq other = (com.netty.study.proto.GetStudentByUserTypeReq) obj;

    if (!getUsertype()
        .equals(other.getUsertype())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getUsertype().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.netty.study.proto.GetStudentByUserTypeReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.netty.study.proto.GetStudentByUserTypeReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.netty.study.proto.GetStudentByUserTypeReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.netty.study.proto.GetStudentByUserTypeReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.netty.study.proto.GetStudentByUserTypeReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.netty.study.proto.GetStudentByUserTypeReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.netty.study.proto.GetStudentByUserTypeReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.netty.study.proto.GetStudentByUserTypeReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.netty.study.proto.GetStudentByUserTypeReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.netty.study.proto.GetStudentByUserTypeReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.netty.study.proto.GetStudentByUserTypeReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.netty.study.proto.GetStudentByUserTypeReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.netty.study.proto.GetStudentByUserTypeReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.netty.study.proto.GetStudentByUserTypeReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.netty.study.proto.GetStudentByUserTypeReq)
      com.netty.study.proto.GetStudentByUserTypeReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netty.study.proto.StudentProto.internal_static_com_netty_study_proto_GetStudentByUserTypeReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netty.study.proto.StudentProto.internal_static_com_netty_study_proto_GetStudentByUserTypeReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netty.study.proto.GetStudentByUserTypeReq.class, com.netty.study.proto.GetStudentByUserTypeReq.Builder.class);
    }

    // Construct using com.netty.study.proto.GetStudentByUserTypeReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      usertype_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.netty.study.proto.StudentProto.internal_static_com_netty_study_proto_GetStudentByUserTypeReq_descriptor;
    }

    @java.lang.Override
    public com.netty.study.proto.GetStudentByUserTypeReq getDefaultInstanceForType() {
      return com.netty.study.proto.GetStudentByUserTypeReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.netty.study.proto.GetStudentByUserTypeReq build() {
      com.netty.study.proto.GetStudentByUserTypeReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.netty.study.proto.GetStudentByUserTypeReq buildPartial() {
      com.netty.study.proto.GetStudentByUserTypeReq result = new com.netty.study.proto.GetStudentByUserTypeReq(this);
      result.usertype_ = usertype_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.netty.study.proto.GetStudentByUserTypeReq) {
        return mergeFrom((com.netty.study.proto.GetStudentByUserTypeReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.netty.study.proto.GetStudentByUserTypeReq other) {
      if (other == com.netty.study.proto.GetStudentByUserTypeReq.getDefaultInstance()) return this;
      if (!other.getUsertype().isEmpty()) {
        usertype_ = other.usertype_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.netty.study.proto.GetStudentByUserTypeReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.netty.study.proto.GetStudentByUserTypeReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object usertype_ = "";
    /**
     * <code>string usertype = 1;</code>
     * @return The usertype.
     */
    public java.lang.String getUsertype() {
      java.lang.Object ref = usertype_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        usertype_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string usertype = 1;</code>
     * @return The bytes for usertype.
     */
    public com.google.protobuf.ByteString
        getUsertypeBytes() {
      java.lang.Object ref = usertype_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        usertype_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string usertype = 1;</code>
     * @param value The usertype to set.
     * @return This builder for chaining.
     */
    public Builder setUsertype(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      usertype_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string usertype = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsertype() {
      
      usertype_ = getDefaultInstance().getUsertype();
      onChanged();
      return this;
    }
    /**
     * <code>string usertype = 1;</code>
     * @param value The bytes for usertype to set.
     * @return This builder for chaining.
     */
    public Builder setUsertypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      usertype_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.netty.study.proto.GetStudentByUserTypeReq)
  }

  // @@protoc_insertion_point(class_scope:com.netty.study.proto.GetStudentByUserTypeReq)
  private static final com.netty.study.proto.GetStudentByUserTypeReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.netty.study.proto.GetStudentByUserTypeReq();
  }

  public static com.netty.study.proto.GetStudentByUserTypeReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetStudentByUserTypeReq>
      PARSER = new com.google.protobuf.AbstractParser<GetStudentByUserTypeReq>() {
    @java.lang.Override
    public GetStudentByUserTypeReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetStudentByUserTypeReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetStudentByUserTypeReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetStudentByUserTypeReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.netty.study.proto.GetStudentByUserTypeReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

