// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.netty.study.proto;

public interface GetStudentByUserAgeResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.netty.study.proto.GetStudentByUserAgeRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string usercode = 1;</code>
   * @return The usercode.
   */
  java.lang.String getUsercode();
  /**
   * <code>string usercode = 1;</code>
   * @return The bytes for usercode.
   */
  com.google.protobuf.ByteString
      getUsercodeBytes();
}
