// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.netty.study.proto;

public interface GetStudentByUserIdReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.netty.study.proto.GetStudentByUserIdReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userid = 1;</code>
   * @return The userid.
   */
  java.lang.String getUserid();
  /**
   * <code>string userid = 1;</code>
   * @return The bytes for userid.
   */
  com.google.protobuf.ByteString
      getUseridBytes();
}
