// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.netty.study.proto;

public interface GetStudentByUserIdResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.netty.study.proto.GetStudentByUserIdRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realname = 1;</code>
   * @return The realname.
   */
  java.lang.String getRealname();
  /**
   * <code>string realname = 1;</code>
   * @return The bytes for realname.
   */
  com.google.protobuf.ByteString
      getRealnameBytes();

  /**
   * <code>string userid = 2;</code>
   * @return The userid.
   */
  java.lang.String getUserid();
  /**
   * <code>string userid = 2;</code>
   * @return The bytes for userid.
   */
  com.google.protobuf.ByteString
      getUseridBytes();

  /**
   * <code>string birthday = 3;</code>
   * @return The birthday.
   */
  java.lang.String getBirthday();
  /**
   * <code>string birthday = 3;</code>
   * @return The bytes for birthday.
   */
  com.google.protobuf.ByteString
      getBirthdayBytes();
}
