// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.netty.study.proto;

public interface GetStudentByUserTypeResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.netty.study.proto.GetStudentByUserTypeRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 usernumber = 1;</code>
   * @return The usernumber.
   */
  int getUsernumber();
}
