// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.netty.study.proto;

public interface GetStudentByUserTypeReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.netty.study.proto.GetStudentByUserTypeReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string usertype = 1;</code>
   * @return The usertype.
   */
  java.lang.String getUsertype();
  /**
   * <code>string usertype = 1;</code>
   * @return The bytes for usertype.
   */
  com.google.protobuf.ByteString
      getUsertypeBytes();
}
