// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.netty.study.proto;

public interface GetStudentByUserAgeReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.netty.study.proto.GetStudentByUserAgeReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 userage = 1;</code>
   * @return The userage.
   */
  int getUserage();
}
