// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.netty.study.proto;

/**
 * Protobuf type {@code com.netty.study.proto.GetStudentByUserAgeRes}
 */
public  final class GetStudentByUserAgeRes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.netty.study.proto.GetStudentByUserAgeRes)
    GetStudentByUserAgeResOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetStudentByUserAgeRes.newBuilder() to construct.
  private GetStudentByUserAgeRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetStudentByUserAgeRes() {
    usercode_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetStudentByUserAgeRes();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetStudentByUserAgeRes(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            usercode_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.netty.study.proto.StudentProto.internal_static_com_netty_study_proto_GetStudentByUserAgeRes_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.netty.study.proto.StudentProto.internal_static_com_netty_study_proto_GetStudentByUserAgeRes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.netty.study.proto.GetStudentByUserAgeRes.class, com.netty.study.proto.GetStudentByUserAgeRes.Builder.class);
  }

  public static final int USERCODE_FIELD_NUMBER = 1;
  private volatile java.lang.Object usercode_;
  /**
   * <code>string usercode = 1;</code>
   * @return The usercode.
   */
  public java.lang.String getUsercode() {
    java.lang.Object ref = usercode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      usercode_ = s;
      return s;
    }
  }
  /**
   * <code>string usercode = 1;</code>
   * @return The bytes for usercode.
   */
  public com.google.protobuf.ByteString
      getUsercodeBytes() {
    java.lang.Object ref = usercode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      usercode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getUsercodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, usercode_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUsercodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, usercode_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.netty.study.proto.GetStudentByUserAgeRes)) {
      return super.equals(obj);
    }
    com.netty.study.proto.GetStudentByUserAgeRes other = (com.netty.study.proto.GetStudentByUserAgeRes) obj;

    if (!getUsercode()
        .equals(other.getUsercode())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERCODE_FIELD_NUMBER;
    hash = (53 * hash) + getUsercode().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.netty.study.proto.GetStudentByUserAgeRes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.netty.study.proto.GetStudentByUserAgeRes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.netty.study.proto.GetStudentByUserAgeRes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.netty.study.proto.GetStudentByUserAgeRes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.netty.study.proto.GetStudentByUserAgeRes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.netty.study.proto.GetStudentByUserAgeRes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.netty.study.proto.GetStudentByUserAgeRes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.netty.study.proto.GetStudentByUserAgeRes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.netty.study.proto.GetStudentByUserAgeRes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.netty.study.proto.GetStudentByUserAgeRes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.netty.study.proto.GetStudentByUserAgeRes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.netty.study.proto.GetStudentByUserAgeRes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.netty.study.proto.GetStudentByUserAgeRes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.netty.study.proto.GetStudentByUserAgeRes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.netty.study.proto.GetStudentByUserAgeRes)
      com.netty.study.proto.GetStudentByUserAgeResOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netty.study.proto.StudentProto.internal_static_com_netty_study_proto_GetStudentByUserAgeRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netty.study.proto.StudentProto.internal_static_com_netty_study_proto_GetStudentByUserAgeRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netty.study.proto.GetStudentByUserAgeRes.class, com.netty.study.proto.GetStudentByUserAgeRes.Builder.class);
    }

    // Construct using com.netty.study.proto.GetStudentByUserAgeRes.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      usercode_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.netty.study.proto.StudentProto.internal_static_com_netty_study_proto_GetStudentByUserAgeRes_descriptor;
    }

    @java.lang.Override
    public com.netty.study.proto.GetStudentByUserAgeRes getDefaultInstanceForType() {
      return com.netty.study.proto.GetStudentByUserAgeRes.getDefaultInstance();
    }

    @java.lang.Override
    public com.netty.study.proto.GetStudentByUserAgeRes build() {
      com.netty.study.proto.GetStudentByUserAgeRes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.netty.study.proto.GetStudentByUserAgeRes buildPartial() {
      com.netty.study.proto.GetStudentByUserAgeRes result = new com.netty.study.proto.GetStudentByUserAgeRes(this);
      result.usercode_ = usercode_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.netty.study.proto.GetStudentByUserAgeRes) {
        return mergeFrom((com.netty.study.proto.GetStudentByUserAgeRes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.netty.study.proto.GetStudentByUserAgeRes other) {
      if (other == com.netty.study.proto.GetStudentByUserAgeRes.getDefaultInstance()) return this;
      if (!other.getUsercode().isEmpty()) {
        usercode_ = other.usercode_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.netty.study.proto.GetStudentByUserAgeRes parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.netty.study.proto.GetStudentByUserAgeRes) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object usercode_ = "";
    /**
     * <code>string usercode = 1;</code>
     * @return The usercode.
     */
    public java.lang.String getUsercode() {
      java.lang.Object ref = usercode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        usercode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string usercode = 1;</code>
     * @return The bytes for usercode.
     */
    public com.google.protobuf.ByteString
        getUsercodeBytes() {
      java.lang.Object ref = usercode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        usercode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string usercode = 1;</code>
     * @param value The usercode to set.
     * @return This builder for chaining.
     */
    public Builder setUsercode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      usercode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string usercode = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsercode() {
      
      usercode_ = getDefaultInstance().getUsercode();
      onChanged();
      return this;
    }
    /**
     * <code>string usercode = 1;</code>
     * @param value The bytes for usercode to set.
     * @return This builder for chaining.
     */
    public Builder setUsercodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      usercode_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.netty.study.proto.GetStudentByUserAgeRes)
  }

  // @@protoc_insertion_point(class_scope:com.netty.study.proto.GetStudentByUserAgeRes)
  private static final com.netty.study.proto.GetStudentByUserAgeRes DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.netty.study.proto.GetStudentByUserAgeRes();
  }

  public static com.netty.study.proto.GetStudentByUserAgeRes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetStudentByUserAgeRes>
      PARSER = new com.google.protobuf.AbstractParser<GetStudentByUserAgeRes>() {
    @java.lang.Override
    public GetStudentByUserAgeRes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetStudentByUserAgeRes(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetStudentByUserAgeRes> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetStudentByUserAgeRes> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.netty.study.proto.GetStudentByUserAgeRes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

